### ISSUE TITLE
location of subscriptions

### ISSUE THREAD

**Issue by DieselDriver** [xaverW/MTPlayer#1]
Hello,

in which folder or file will the subscriptions be stored?

Thanks, a lot.

**Comment by xaverW** [comment]
Hello,

on the website is a description (only in german) which describes, how
the download of files can be managed.

https://www.p2tools.de/mtplayer/manual/set.html
https://www.p2tools.de/assets/img_mtplayer_manual/mtplayer-004.png


In the set "Speichern" can you set the downloadpath: "Zielpfad" and the
name of the downloaded file: "Zieldateiname".
For the filename you can use shortcuts, witch are also on the website
declared.

Hope you understand my "english" :)

Greetings
Xaver



Am Tue, 31 Mar 2020 10:29:55 -0700
schrieb DieselDriver <notifications@github.com>:

> Hello,
> 
> in which folder or file will the subscriptions be stored?
> 
> Thanks, a lot.
>
