### ISSUE TITLE
Nach Aktion springt der "Zeiger" wieder an den Anfang der Liste

### ISSUE THREAD

**Issue by W11T** [xaverW/MTPlayer#10]
In V13 ist mir aufgefallen, dass, wenn man aus einem Profil einen Film zur Ansicht oder zum Herunterladen anklickt, der "Zeiger" wieder an den Anfang der Liste springt.
Bei langen Listen ist es ziemlich mühsam, dann wieder die Stelle zu finden um da weiterzumachen.

**Comment by xaverW** [comment]
Wenn der Filter "gesehene nicht anzeigen" aktiv ist, wird der Film nach Start ausgeblendet und der erste Film in der Tabelle wird markiert. Es sollte dann also der Film davor/danach angezeigt werden? Wäre wahrscheinlich praktischer.
Werds einbauen.

**Comment by W11T** [comment]
Prima!
Bei der Gelegenheit:
Danke, dass Du dieses Programm mit uns teilst!

**Comment by LinuxOpa** [comment]
> Prima! Bei der Gelegenheit: Danke, dass Du dieses Programm mit uns teilst!

Dem schließe ich mich selbstredend an.

**Comment by xaverW** [comment]
in der aktuellen Daily ist das geändert. Wenn sehr viele Zeilen als "gelesen" markiert werden, ist der Anzeigebereich aber nicht mehr die letzte Zeile davor, mal schauen was mir da noch einfällt dazu :)

**Comment by LinuxOpa** [comment]
> in der aktuellen Daily ist das geändert. Wenn sehr viele Zeilen als "gelesen" markiert werden, ist der Anzeigebereich aber nicht mehr die letzte Zeile davor, mal schauen was mir da noch einfällt dazu :)

schon im Test...

**Comment by xaverW** [comment]
geht in der aktuellen daily wieder. Es wird der Film vor dem entfernten selektiert.
