### ISSUE TITLE
kleine Wunschliste [enhancement]

### ISSUE THREAD

**Issue by LinuxOpa** [xaverW/MTPlayer#11]
### **Wünsche:**

✓ In Einstellungen "nur 1 Instanz" Häkchen um doppelten Programmstart zu verhindern
✓ Für "Thema direkt in Blacklist eintragen" einen Shortcut Ctrl-Shift-B
✓Auswahl (Häkchen) "Immer Filmliste komplett herunterladen"
✓ Einen Menüpunkt in Blacklist "suchen"
✓ Einen Menüpunkt in Blacklist "Zeile in Filterliste verschieben"
✓ "Irgendwo" in Suche in BL/FL
✓ Infozeilen im Filmlistenfenster fix ein/ausblendbar über die ganze Breite (hat Opa übersehen Alt-I)
✓ Schalter  -m,--minimize         start minimized
✓ Für "warten auf Download Ende" einen Minimize-Button

21.03.2023
da die Filmliste eh zyklisch abgefragt wird, bitte bei neuen Daten gleich aktualisieren ala "linke Maustaste"=Diff laden

[![5.jpg](https://i.postimg.cc/TP0sMztc/5.jpg)](https://postimg.cc/944byn54)

**Comment by LinuxOpa** [comment]
- Auswahl (Häkchen) "Immer Filmliste komplett herunterladen"

**Comment by xaverW** [comment]
Hi,

Button "Filmliste" mit der RECHTEN Maustaste, dann wird immer komplett
geladen :)



Am Mon, 13 Mar 2023 02:55:35 -0700
schrieb LinuxOpa ***@***.***>:

> - Auswahl (Häkchen) "Immer Filmliste komplett herunterladen"
>

**Comment by LinuxOpa** [comment]
> Hi, Button "Filmliste" mit der RECHTEN Maustaste, dann wird immer komplett geladen :) Am Mon, 13 Mar 2023 02:55:35 -0700 schrieb LinuxOpa ***@***.***>:
> […](#)
> - Auswahl (Häkchen) "Immer Filmliste komplett herunterladen"

bekannt, danke, aber möchte ich bei jedem Start automatisch, wenn es geht; ist nicht dringend

**Comment by xaverW** [comment]
Hi,

das ist jetzt drin:



Am Mon, 13 Mar 2023 02:55:35 -0700
schrieb LinuxOpa ***@***.***>:

> - Auswahl (Häkchen) "Immer Filmliste komplett herunterladen"
>

**Comment by xaverW** [comment]
Hi,

das ist jetzt drin:

* Markierung der gesehenen Filme korrigiert
* Blacklist-Dialog erweitert
* In den Einstellungen kann eine Lock-Datei eingeschaltet werden: Es
  wird dann sichergestellt, dass nur eine Instanz vom Programm läuft
* Ein neues ShortCut: Ctrl+Shift+B zum direkten Hinzufügen des Themas
  in die Blacklist
* Ein neuer Programm-Schalter: -u, gibt dann eine Download-URL für die
  Filmliste vor (~zum Testen des Programms)
* ...



"Komplette Liste" in den Einstellungen will ich nicht machen, mit der
Diff-Liste soll ja auch verhindert werden, das die Datenmenge der
Downloads nicht ausufert.

Du kannst mit dem neuen Schalter aber beim Programmstart dann die URL
vorgeben, die wird dann immer verwendet. Macht also das gleiche.

Die DownloadURLs sind:

https://liste.mediathekview.de/Filmliste-akt.xz
https://liste.mediathekview.de/Filmliste-diff.xz

btw: Bin am überlegen auf Java 17 umzusteigen?? Wäre das nächste LTS
nach Java 11. Spricht da was aus deiner Sicht dagegen? Denk dass
auf den Klient-Rechner das eh schon weiter ist (18, 19, ..).

Lg
Xaver





Am Mon, 13 Mar 2023 02:55:35 -0700
schrieb LinuxOpa ***@***.***>:

> - Auswahl (Häkchen) "Immer Filmliste komplett herunterladen"
>

**Comment by LinuxOpa** [comment]
> Blacklist-Dialog erweitert
ich bin wohl blind, sehe gerade den Unterschied nicht - 'n Screenshot per Mail wäre nett 

für die anderen Punkte untertänigsten Dank! :-)

da ich noch Ubuntu 20.04.5 LTS fahre, ist z.Zt 17 aktuell

Lg Detlef

**Comment by xaverW** [comment]
Hi,

ist der Dialog den man unter dem Filmfilter öffnen kann. Da wurden die
FilmFilter zum Laden der Filmliste mit eingefügt.



Am Tue, 14 Mar 2023 10:35:45 -0700
schrieb LinuxOpa ***@***.***>:

> > Blacklist-Dialog erweitert  
> ich bin wohl blind, sehe gerade den Unterschied nicht - 'n Screenshot
> per Mail wäre nett 
> 
> für die anderen Punkte untertänigsten Dank! :-)
> 
> da ich noch Ubuntu 20.04.5 LTS fahre, ist z.Zt 17 aktuell
> 
> Lg Detlef
>

**Comment by LinuxOpa** [comment]
Läuft einwandfrei MTPlayer-13-15__2023.03.14 [![daumen-hoch-64x64.png](https://i.postimg.cc/NGy7JMNs/daumen-hoch-64x64.png)](https://postimg.cc/V58C5YQp)

**Comment by LinuxOpa** [comment]
MTPlayer-13-22__2023.03.18:
1. Suche in Blacklist / Filterliste mag nicht so recht:
[![1.jpg](https://i.postimg.cc/X7zGfV0R/1.jpg)](https://postimg.cc/D81wF306)
[![2.jpg](https://i.postimg.cc/Hsx88rF0/2.jpg)](https://postimg.cc/pywLgLWy)

2. Zeilen in Blacklist / Filterlist löschen wollte nicht funktionieren, die ganze Liste löschen ging

**Comment by xaverW** [comment]
Suche in Blacklist / Filterliste mag nicht so recht:

hast du in einem Blacklistfilter im Feld "Thema/Titel" was eingetragen? Die Suche "Thema/Titel" sucht nur im BlackListFilter im Feld "Thema/Titel"
(werde die Beschriftung änder auf: "Thema-Titel", ist dann vielleicht klarer)

Zeile Löschen: War noch ein Fehler drin, danke

**Comment by LinuxOpa** [comment]
> hast du in einem Blacklistfilter im Feld "Thema/Titel" was eingetragen? Die Suche "Thema/Titel" sucht nur im BlackListFilter im > Feld "Thema/Titel" (werde die Beschriftung änder auf: "Thema-Titel", ist dann vielleicht klarer)

begriffen, **danke**, klappt. :+1:
vielleicht noch ein "Irgendwo" in BL/FL? :grin:

**Comment by LinuxOpa** [comment]
MTPlayer-13-29__2023.03.20.zip  [![daumen-hoch-64x64.png](https://i.postimg.cc/NGy7JMNs/daumen-hoch-64x64.png)](https://postimg.cc/V58C5YQp)

**Comment by LinuxOpa** [comment]
Ich hab mal 'n bischen aufgeräumt, erledigte Beiträge (meine eigenen) gelöscht.
Abgehakte Wünsche siehe ganz am Anfang.

**Comment by xaverW** [comment]
Hi,

> 20.03.2023
> Infozeilen im Filmlistenfenster fix ein/ausblendbar über die ganze
> Breite (Bild nur als Skizze )

ist mir noch nicht ganz klar? Den Infobereich kann man ja
ein-/ausblenden: Menü oder "rechte Maustaste auf "Filme" Tab"

Der soll als kleiner Kasten so wie im Bild angezeigt werden? Oder soll
es als eigener "Dialog" also zweites Fenster angezeigt werden?

Grüße
Xaver





Am Tue, 21 Mar 2023 11:57:17 -0700
schrieb LinuxOpa ***@***.***>:

> Ich hab mal 'n bischen aufgeräumt, erledigte Beiträge (meine eigenen)
> gelöscht. Abgehakte Wünsche siehe ganz am Anfang.
>

**Comment by LinuxOpa** [comment]
so wie hier

[https://static.giga.de/wp-content/uploads/2017/11/MediathekView-1-rcm480x0u.jpg](https://static.giga.de/wp-content/uploads/2017/11/MediathekView-1-rcm480x0u.jpg)

**Comment by xaverW** [comment]
habe in der aktuellen daily die Infos im Infobereich erweitert. Steh aber noch auf der Leitung: War es das was du gemeint hast? Denn einen eigenen Filminfo-Dialog gibt es ja auch schon. (Doppelklich auf einen Film oder Kontextmenü Tabelle).
Und hat sogar ein ShortCut (ctrl+I) :)

**Comment by xaverW** [comment]
✓ Im Filterframe die *Filterliste ala "Blacklist ein/aus/invers" + "Edit" dazugeben

Das gefällt mir nicht so ganz? Denn das hat im Gegensatz zur BlackList ja keine direkte Auswirkung. Es muss ja erst eine neue Filmliste geladen werden, dass man da eine Änderung sieht. Im Blacklist-Dialog ist die 2. Blacklist zum Filtern beim Filmeladen jetzt ja auch enthalten. Ist also auch nur einen Klick weiter entfernt, Oder?

**Comment by LinuxOpa** [comment]
> habe in der aktuellen daily die Infos im Infobereich erweitert. Steh aber noch auf der Leitung: War es das was du gemeint hast? Denn einen eigenen Filminfo-Dialog gibt es ja auch schon. (Doppelklich auf einen Film oder Kontextmenü Tabelle).

MIST, habe ALT-I nicht gesehen! Das ist es.
Untertänigstes Sorry!!!

[![sorry.gif](https://i.postimg.cc/0yMHhnQH/sorry.gif)](https://postimg.cc/k2CcbxWx)

**Comment by LinuxOpa** [comment]
> ✓ Im Filterframe die *Filterliste ala "Blacklist ein/aus/invers" + "Edit" dazugeben
> 
> Das gefällt mir nicht so ganz? Denn das hat im Gegensatz zur BlackList ja keine direkte Auswirkung. Es muss ja erst eine neue Filmliste geladen werden, dass man da eine Änderung sieht. Im Blacklist-Dialog ist die 2. Blacklist zum Filtern beim Filmeladen jetzt ja auch enthalten. Ist also auch nur einen Klick weiter entfernt, Oder?

vergiss, ist gut so

**Comment by xaverW** [comment]
oder meinst du das so??
![Filme](https://user-images.githubusercontent.com/8464624/227283307-573974a4-55d1-4ab9-8dbf-80c03ad89de0.png)

**Comment by LinuxOpa** [comment]
> oder meinst du das so?? ![Filme](https://user-images.githubusercontent.com/8464624/227283307-573974a4-55d1-4ab9-8dbf-80c03ad89de0.png)

MIST, habe ALT-I nicht gesehen! Das ist es.
Untertänigstes Sorry!!! [![sorry.gif](https://i.postimg.cc/0yMHhnQH/sorry.gif)](https://postimg.cc/k2CcbxWx)
V. 23.03.23  [![daumen-hoch-64x64.png](https://i.postimg.cc/NGy7JMNs/daumen-hoch-64x64.png)](https://postimg.cc/V58C5YQp)

**Comment by xaverW** [comment]
ja, jetzt klar, muss ich mir mal ansehen wie das praktisch funktioniert,
dass es sich dann nicht beißt mit der selektierten Zeile??



Am Thu, 23 Mar 2023 10:04:52 -0700
schrieb LinuxOpa ***@***.***>:

> > habe in der aktuellen daily die Infos im Infobereich erweitert.
> > Steh aber noch auf der Leitung: War es das was du gemeint hast?
> > Denn einen eigenen Filminfo-Dialog gibt es ja auch schon.
> > (Doppelklich auf einen Film oder Kontextmenü Tabelle).  
> 
> Doppelklick ist bekannt...
> 
> schau oben, im unteren Fenster steht "Wunderland - blabla" darunter
> der Link schön wäre es, gleich beim Wandern mit dem Cursor, also die
> blau hinterlegten Zeile,  über die Filmliste, gleich die Info unten
> mit aktualisiert würde; aus Thema oder Titlel geht meist der Inhalt
> nicht hervor. Klarer?
>

**Comment by LinuxOpa** [comment]
> ja, jetzt klar, muss ich mir mal ansehen wie das praktisch funktioniert, dass es sich dann nicht beißt mit der selektierten Zeile?? Am Thu, 23 Mar 2023 10:04:52 -0700 schrieb LinuxOpa ***@***.***>:
> […](#)
> > habe in der aktuellen daily die Infos im Infobereich erweitert. > Steh aber noch auf der Leitung: War es das was du gemeint hast? > Denn einen eigenen Filminfo-Dialog gibt es ja auch schon. > (Doppelklich auf einen Film oder Kontextmenü Tabelle). Doppelklick ist bekannt... schau oben, im unteren Fenster steht "Wunderland - blabla" darunter der Link schön wäre es, gleich beim Wandern mit dem Cursor, also die blau hinterlegten Zeile, über die Filmliste, gleich die Info unten mit aktualisiert würde; aus Thema oder Titlel geht meist der Inhalt nicht hervor. Klarer?

alles gut so, nix ändern, hatte alt-i übersehen!

[![sorry.gif](https://i.postimg.cc/0yMHhnQH/sorry.gif)](https://postimg.cc/k2CcbxWx)

**Comment by LinuxOpa** [comment]
V. 23.03.26  [![daumen-hoch-64x64.png](https://i.postimg.cc/NGy7JMNs/daumen-hoch-64x64.png)](https://postimg.cc/V58C5YQp)
