### ISSUE TITLE
die Webseite MTPlayer: Mobil wird unvollständig angezeigt

### ISSUE THREAD

**Issue by LinuxOpa** [xaverW/MTPlayer#13]
Die Mobile Seite wird unvollständig angezeigt, es ist keine Auswahl möglich (Download etc.):
[![mobil-1.jpg](https://i.postimg.cc/QtHWkj3F/mobil-1.jpg)](https://postimg.cc/34QR35Wh)
[![mobil-2.jpg](https://i.postimg.cc/26ML0gk2/mobil-2.jpg)](https://postimg.cc/DJQzZjbX)

nach umschalten in Desktop-Modus wird vollständig angezeigt:

[![mobil-3.jpg](https://i.postimg.cc/qvwtPNBt/mobil-3.jpg)](https://postimg.cc/RW3VfVH9)

nur als Hinweis

**Comment by xaverW** [comment]
Danke, kommt auf die LIste der todo :)
