### ISSUE TITLE
Schriftgrösse zu hoch Linux

### ISSUE THREAD

**Issue by GaVenga** [xaverW/MTPlayer#15]
Manjaro testing, Gnome
Die Schriftgröße der Version vom 29.04.2023 ist viel zu hoch,
ich muss Grösse 6 einstellen, um arbeiten zu können...
System benutzt java 20 und Wayland Skalierung 100%

**Comment by xaverW** [comment]
ich habe das jetzt bei mir versucht, nachzustellen:
arch mit Java:

Vendor:  Oracle Corporation
VM-Name: OpenJDK 64-Bit Server VM
Version: 20.0.1
Feature: 20  Interim: 0  Update: 1  Patch: 0
Runtimeversion: 20.0.1+9-29

und da stimmt die Schriftgröße. Wenn in den Einstellungen keine feste Schriftgröße vorgegeben wird, setzt das Programm auch keine. Dann ist es alleine Jave überlassen, welche Schriftgröße es verwendet. Die sollte sich dann nach der des BS richten.

Wenn ich in den Einstellungen eine Größe vorgebe, wird auch die dann richtig angezeigt.

Wenn du in den Einstellungen die "Schriftgöße" ausschaltest, dann wird sie zu groß angezeigt und wenn du in den Einstellugen Größe 6 vorgibst, hast du die normale Systemgröße? Wie ist es bei anderen Javaprogrammen?

**Comment by GaVenga** [comment]
Wenn du in den Einstellungen die "Schriftgöße" ausschaltest, dann wird sie zu groß angezeigt und wenn du in den Einstellugen Größe 6 vorgibst, hast du die normale Systemgröße? Wie ist es bei anderen Javaprogrammen?
Genau so.
Das einzige Programm, welches Java 20  benutzt, ist JOSM - und das sieht normal aus.
Auf die Schnelle fällt mir kein Programm ein, welches java benutzt...

sudo pacman -sS java | grep jre
extra/jre-openjdk 20.0.1.u9-3 [Installiert]
extra/jre-openjdk-headless 20.0.1.u9-3 [Installiert]
extra/jre11-openjdk 11.0.19.u7-1
extra/jre11-openjdk-headless 11.0.19.u7-1
extra/jre17-openjdk 17.0.7.u7-1
extra/jre17-openjdk-headless 17.0.7.u7-1
extra/jre8-openjdk 8.372.u07-1
extra/jre8-openjdk-headless 8.372.u07-1
chaotic-aur/intellij-idea-ultimate-edition-jre 2023.1.1-1
chaotic-aur/jre 20-1
chaotic-aur/jre8 8u361-1
.
java -version        
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)

**Comment by GaVenga** [comment]
Kommando zurück!
Nachdem der MTPlayer in einem anderen Profil funktioniert,
habe ich folgende Datei gelöscht:
.config/dconf/user - also GNOME ==> alle Einstellungen  zurückgesetzt.
Muss alles neu Konfigurieren - Ursache war eine Spielerei mit "fractional scaling"
nach der Zurücknahme von "fs" meinte MTPlayer, er müsse unbedingt auf 150 % skalieren...

**Comment by GaVenga** [comment]
Nun habe ich meine Missetat gefunden:

im dconf-editor wegen Wayland den Eintrag:
/org/gnome/desktop/interface/scaling-factor
von default null auf zwei gestellt.
Ein Programm wollte das so, es gab jedoch eine ander Möglichkeit;
die Änderung hatte ich nicht zurückgenommen - und schon ist MTPlayer schön gross geworden....
