### ISSUE TITLE
Dateiname wird nicht richtig gespeichert

### ISSUE THREAD

**Issue by GaVenga** [xaverW/MTPlayer#16]
Wenn ich diese Filme herunterlade mit Beta-V14 oder V13:
Titel:
Science Busters - Wer nichts weiß muss alles glauben (1/13) - Klimafittes Österreich

dann wird das gespeichert als:
Science_Busters-Science_Busters_-_Wer_nic-0596494116.mp4
Möchte jedoch haben:
Science Busters - Wer nichts weiß muss alles glauben (1/13) - Klimafittes Österreich.mp4

**Comment by xaverW** [comment]
in den Einstellungen->Aufzeichnen->Speicherziel kann man die max. Länge des Dateinamens festlegen (und auch der einzelen Felder) und die ist Standarmäßig beschränkt. Das kann dort aber geändert werden
