### ISSUE TITLE
Beim Wechsel der Filterprofile geht die Filmliste nicht in ihre Ausgangsposition

### ISSUE THREAD

**Issue by wallobit** [xaverW/MTPlayer#17]
Beispiel:
Das Datum ist auf absteigende Sortierung eingestellt
Ich benutze einen Filter, der alle Filme ab einer bestimmten Länge anzeigt - Der neueste Film ist ganz oben auf der Liste.
Ich gebe in das Suchfeld des Filters einen  Filmtitel ein - Dieser wird mir gefiltert angezeigt.
Jetzt stelle ich die alte Filtereinstellung wieder her.
Problem:
Es werden wieder alle Filme ab einer bestimmten Länge nach absteigendem Datum angezeigt, aber der oberste Film in der Liste ist die Position des letzten Suchergebnisses.  Zum Anfang dieser Liste muss ich scrollen. Beim Wechsel der Filter ist dieses etwas irritierend.
Lösungsvorschlag:
Könnte man bei einem Wechsel der Filter das Anzeigeverhalten so ändern, dass die Listenanzeige sich nicht nach der vorherigen Suche richtet, sondern auf Anfang geht?

**Comment by xaverW** [comment]
klar, wäre möglich. Gibts da noch weitere Meinungen dazu? Wann soll die letzte Pos genommen werden, wann an den Anfang der Liste? Es waren User-Wünsche immer die letzte Pos nach dem Filtern wieder einzustellen.

* Beim Filtern immer die letzte Pos anzeigen
* Beim Einstellen eines gespeicherten Filters an  den Anfang der Liste
* Beim Vor- Zurückblätern in der Filter-Historie letzte Pos
????

**Comment by LinuxOpa** [comment]
immer die letzte Pos nach dem Filtern wieder einstellen.

wäre meins

**Comment by wallobit** [comment]
Kurze Präzisierung meinerseits:
Erst einmal finde ich die Filterprofile im MTPlayer sehr gut durchdacht und hilfreich. Auch sorgt das aufrufbare Fenster mit den Filterprofilen für eine gute Übersicht.
Ich interpretiere die einzelnen Profile als völlig unabhängig, ohne auf vorherige Suchen bezug zu nehmen. Also Filterprofil auswählen und die Anzeige des ersten Ergebnisses in der Liste oben richtet sich ausschließlich nach der Sortierungseinstellung. So kann man dann auch in dem frei schwebenden Filterprofil-Fenster kurz mal seine Profile durchklicken, ohne zwischendurch scrollen zu müssen.
Wer anderer Meinung ist, kann das ruhig mal begründen. Sorgt für eine fruchtbare Diskussion.
xaverW, Du hast es da sicherlich nicht leicht: Neue User, neue Meinungen.
Viele Grüße

**Comment by ewrs** [comment]
Ich habe beim Ändern des Filters auch erwartet, dass ich ein "frisches" Suchergebnis bekomme, also am Anfang der Liste stehe. Das aktuelle Programmverhalten hat mich beim ersten Mal etwas irritiert.

Was ist denn der Vorteil daran, die letzte Position beizubehalten?

**Comment by W11T** [comment]
Hallo!
Ich glaube, da gibt es auch noch einen Zusammenhang mit "[Nach Aktion springt der "Zeiger" wieder an den Anfang der Liste](https://github.com/xaverW/MTPlayer/issues/10#issue-1617606212)".
Ich habe einige Filterprofile, die viele Treffer liefern, nach Thema sortiert.
Wenn ich dann einen Film herunterlade, verschwindet er ja aus der Liste. Teilweise springt der Zeiger dann auf den Film davor und teilweise ganz an den Anfang. So genau habe ich das Verhalten noch nicht verstanden.
Es ist ziemlich lästig, die ganze lange Liste wieder von vorne abzusuchen.

Daher wäre ich dafür, an der letzten Stelle weiter zu machen.

Mein Szenario wäre, ich habe eine lange Liste, stehe mittendrin, sortiere einmal um, um etwas zu vergleichen, und sortiere dann wieder in der Folge wie vorher. Wenn ich dann wieder komplett von vorne runterblättern müsste, fände ich das schon nervig.

Bei kleinen Trefferliste sollte das ja alles kein Thema sein.

**Comment by LinuxOpa** [comment]
>  
> Daher wäre ich dafür, an der letzten Stelle weiter zu machen.
> 
dafür

**Comment by wallobit** [comment]
Ich glaube, wir haben jetzt alle begriffen, dass LinuxOpa für die bisherige Lösung ist.

Zurück zur Diskussion. Ich habe befürchtet, dass jeder anscheinend erwartet, die Entwicklung des Programms hat sich nach seiner (speziellen) Arbeitsweise zu richten. Ich nehme mich da nicht aus. Weiter bringt uns das wohl nicht. Man könnte abstimmen; meiner Meinung nach keine gute Idee. Im Moment stehts wohl 2:2.

Ich würde fragen und dann entscheiden: Entspricht das Verhalten der Liste nach der Suche (noch) der Philosophie des klaren und übersichtlichen Konzepts, das MTPlayer von anderen unterscheidet? Ist das Verhalten logisch? Ist das Verhalten irritierend? 

Und wenn sich abzeichnet, dass sich gute Argumente! für beide Ansätze finden, könnte das vielleicht auch mit einer Option in den Sucheinstellungen für beide Möglichkeiten geregelt werden (Cursor immer an den Anfang der Liste EIN/AUS).

**Comment by W11T** [comment]
> ..., sondern auf Anfang geht?

Was geschieht denn, wenn Du die Taste "Pos1" benutzt?

**Comment by xaverW** [comment]
die Tasten "pos1" und "ende" setzten den ersten und letzten Eintrag in der Tabelle.

Ich würde eher dazu neigen, dass nach dem Suchen wieder die letzte Pos ausgewählt ist, könnte mich aber mit beiden Lösungen anfreunden.

> vielleicht auch mit einer Option in den Sucheinstellungen für beide Möglichkeiten geregelt werden (Cursor immer an den Anfang der Liste EIN/AUS).

und das wäre natürlich auch möglich: nach jedem Filtern? oder nur nach dem Ändern/Einstellen eines gespeicherten Filters?

**Comment by ewrs** [comment]
Option klingt gut. Ein zentraler Schalter zum Einstellen, ob die letzte Position beibehalten oder an den Listenanfang gesprungen werden soll, müsste eigentlich reichen. Und dann bei jeder Aktualisierung des Suchergebnisses entsprechend verfahren.

Damit sollte sich am bisherigen Verhalten nichts ändern und das "nach oben springen" wäre nur eine zusätzliche Möglichkeit.

**Comment by skyteddy** [comment]
> 



> Ich interpretiere die einzelnen Profile als völlig unabhängig, ohne auf vorherige Suchen bezug zu nehmen. Also Filterprofil auswählen und die Anzeige des ersten Ergebnisses in der Liste oben richtet sich ausschließlich nach der Sortierungseinstellung.

Genau so sehe ich das auch. Mich stört das bisherige Verhalten auch immer wieder auf's Neue.

**Comment by W11T** [comment]
Ich glaube, ich verstehe die Diskussion nicht.

Öffne ich ein Filterprofil, steht die Auswahl auf dem ersten Eintrag oben.

Ist die Liste, sagen wir mal, nach Größen sortiert und ein Film interessiert mich und ich möchte wissen, ob es zu dem Thema weitere Filme gibt, dann sortiere ich nach Thema. 
Springt dann die Marke wieder an den Anfang, muss ich mir den Film erst wieder suchen.
Bleibt er dagegen markiert, sehe ich sofort die anderen Filme zu dem Thema darüber und/oder darunter.

Mir geht es mehr um die downloads. Finde ich einen Film in einer großen Liste und lade ihn herunter, wird er in den Standardeinstellungen als gelesen aus der Liste entfernt. Da ist es praktisch, dass die Markierung auf dem Film darüber oder darunter bleibt, damit ich an der Stelle weiter blättern kann.
Würde die Markierung nach oben springen, müsste ich wieder lange nach der Position suchen an der ich vorher war.

Noch einmal die Frage nach der Pos1-Taste. Wenn ihr darauf drückt, habt ihr dann nicht den Effekt, den ihr haben möchtet?

**Comment by wallobit** [comment]
> Ich glaube, ich verstehe die Diskussion nicht.
> Öffne ich ein Filterprofil, steht die Auswahl auf dem ersten Eintrag oben.

Ich stimme Dir zu und fürchte leider auch, dass Du die Diskussion nicht verstehst.

Es hat sich schon längst herauskristallisiert, dass die UserInnen unterschiedlich mit dem Programm arbeiten. Wiederholungen des eigenen Filteransatzes helfen nicht weiter. Wenn Du die Einträge aufmerksam liest, wirst Du feststellen, dass wir eigentlich schon weiter sind. 

Die Frage nach der Pos1-Taste interpretiere ich daher mal als kleinen Scherz. Mal zurückgescherzt: Wenn Du lange nach der vorherigen Position suchst: Warum benutzt Du dafür keine Bookmarks?

**Comment by wallobit** [comment]
> Option klingt gut. Ein zentraler Schalter zum Einstellen, ob die letzte Position beibehalten oder an den Listenanfang gesprungen werden soll, müsste eigentlich reichen. Und dann bei jeder Aktualisierung des Suchergebnisses entsprechend verfahren.
Damit sollte sich am bisherigen Verhalten nichts ändern und das "nach oben springen" wäre nur eine zusätzliche Möglichkeit.

ewrs hat es auf den Punkt gebracht. Bin jetzt auch für diesen Ansatz.

**Comment by ewrs** [comment]
@W11T: Da war meine Formulierung anscheinend etwas mißverständlich. Wir hatten über das Verhalten beim Ändern/Wechseln des Filterprofils diskutiert. Nur darauf bezieht sich meine Aussage:

> bei jeder Aktualisierung des Suchergebnisses entsprechend verfahren

Ich meine jedoch _nicht_, dass sich das Verhalten beim Sortieren oder beim Verschwinden eines heruntergeladenen Films aus der Liste ändern sollte.

**Comment by xaverW** [comment]
wenn ich das jetzt mal (hoffentlich) richtig zusammenfasse: Ich werde in den Filtereinstellungen ein Option einbauen: "Nach dem Filtern an den Anfang der Liste springen". Wenn man einen Filter/Filterprofil ändert, dann wird die erste Tabellenzeile ausgewählt. Ist die Option nicht aktiv, bleibt alles so wie bisher.

Wenn man die Tabelle nach Spalten sortiert oder ein Filme ausgeblendet wird (z.B. Download und Filter "keine Downloads anzeigen"), wird der Film (wie bisher) davor angezeigt (unabhängig von der Option).

![Screenshot_20230817_190224](https://github.com/xaverW/MTPlayer/assets/8464624/84f5d5b6-d72f-4f8a-a815-a69cf196b261)

**Comment by wallobit** [comment]
Genau so, super!

**Comment by xaverW** [comment]
das ist jetzt im aktuellem daily drin.
