### ISSUE TITLE
Keine Hintergrundfarben in der Tabelle im Downloadbereich (Version 14 Build 8, Windows mit Java)

### ISSUE THREAD

**Issue by wallobit** [xaverW/MTPlayer#18]
Die konfigurierbaren Hintergrundfarben werden nicht angezeigt, wenn die Spalte mit den beiden Schaltflächen ausgeblendet wird

**Comment by xaverW** [comment]
danke, habs mir angesehen, geht in der nächsten Daily wieder.

**Comment by xaverW** [comment]
ist drin
