### ISSUE TITLE
Virus in MTPlayer?

### ISSUE THREAD

**Issue by LinuxOpa** [xaverW/MTPlayer#19]
Bitte klären.

[![Bildschirmfoto-vom-2023-10-08-10-27-16.png](https://i.postimg.cc/mD7PF28S/Bildschirmfoto-vom-2023-10-08-10-27-16.png)](https://postimg.cc/xJTfwYrk)

**Comment by xaverW** [comment]
Das kommt von den drei Dateien:

MTPlayer.jar
Treffer 1 von 42

MTPlayer__Windows.exe
Treffer 3 von 72

MTPlayer__Windows__Portable.exe
Treffer 3 von 72

entnimmt man die aus dem zip ist der Rest unauffällig.
0 von 60

Die Treffer kommen von unbekannten AV-Scanner (Jiangmin, Zillya, SentinelOne)  und sind Fehler.

Habe einen schönen Artikel dazu auf Heise.de gefunden:

[https://www.heise.de/select/ct/2023/9/2307617422466145316](https://www.heise.de/select/ct/2023/9/2307617422466145316)

> Dass AV-Software Fehlalarme produ-
ziert, ist unvermeidbar. Denn letztlich be-
steht da immer ein Zielkonflikt zwischen
den zwei zentralen Aufgaben, einerseits
möglichst alle „bösen Dinge“ zu erkennen
und andererseits dabei keine „guten“ zu
erwischen. Ein perfekter Scanner, der alle
Viren entdeckt, ist einfach gebaut: Hält er
schlicht alles für einen Virus, liefert er eine
hundertprozentige Erkennung, aber auf­ 
Kosten einer ebenso so hohen Falsch-Posi-
tiv-Rate.

**Comment by LinuxOpa** [comment]
besser aufgepasst als infiziert
ok 👍
----------------------------------------

*Von: *Xaver ***@***.***>
*An: *xaverW/MTPlayer ***@***.***>
*Kopie: *LinuxOpa ***@***.***>; Author ***@***.***>
*Datum: *08.10.2023 13:47:10
*Betreff: *Re: [xaverW/MTPlayer] Virus in MTPlayer? (Issue #19)
