### ISSUE TITLE
Abo legt trotz OFF Unterordner an

### ISSUE THREAD

**Issue by n3zvtVsJFbECVKsKJDNS** [xaverW/MTPlayer#2]
Hallo zusammen, habe heute auf die neue Version MTplayer 9.0 upgedatet. Leider wird für alle Abos ein Unterordner angelegt, obwohl ich den Schiebeschalter auf Aus gestellt habe. Hat jemand eine Idee, ob ich was falsch mache, oder ob dies gefixt werden muss? VG

**Comment by xaverW** [comment]
Hi,

> Wenn eingeschaltet, werden Downloads aus Abos in einem Unterordner gespeichert. Der Ordnername kann mit der Auswahl festgelegt werden. 

> Ist im Abo ein Abozielpfad angegeben, wird die Einstellung überschrieben. Der Download wird immer in einem Unterordner mit dem im Abozielpfad angegebenen Namen gespeichert.

Du hast im Set den "Unterordner" ausgeschaltet aber sind im Abo evtl. individuelle Unterordner angegeben? Kann das sein? Das hätte dann Vorrang. (ist gedacht, wenn man mal für ein Abo doch einen Unterordner will, so muss man nicht gleich ein neues Set dafür anlegen)

**Comment by n3zvtVsJFbECVKsKJDNS** [comment]
Danke XaverW. Genau so hatte ich es auch verstanden und so war es für jedes Abo auch eingestellt. Irgendwas in dem Update hat die gespeicherten Einstellungen überschrieben. D.b. dass im jeden einzelnen Abo im dropdown-Menü nicht mehr standardmäßig leer bleibt! Ich musste jetzt jedes einzelne Abo neu bearbeiten und dort im dropdown die erste (leere Position) neu auswählen. Nun funktioniert es wieder. Danke für deine schnelle Hilfestellung. Viele Grüße
