### ISSUE TITLE
Unterstützung für Macos

### ISSUE THREAD

**Issue by ghost** [xaverW/MTPlayer#20]
Wäre es möglich auch ein build für macOS zur Verfügung zu stellen? 
Ich bekomme es hin, einen build mit gradle auf meinem Mac zu bauen und auch zum laufen zu bekommen.

**Comment by xaverW** [comment]
Das ist die Version die auf "allen" OS läuft.
MTPlayer-17__2024.06.01.zip

Hier ist lediglich Java mit dabei und das unterscheidet sich für das OS. Die Programmdatei (MTPlayer.jar) ist die selbe wie oben.
MTPlayer-17__Linux.mit.Java__2024.06.01.zip
MTPlayer-17__Windows.mit.Java__2024.06.01.zip

Es gibt also keine angepasste Programmdateien. Es sind aber ein paar Stellen im Programm die für Linux/Windows unterschiedlich sind (z.B. Pfade). Ich habe (wenn MAC erkannt wird) die Einstellungen für Linux dafür übernommen.

Wenn die Programmdatei auf MacOS aber nicht läuft, kann ich leider nicht weiterhelfen. Ich habe keinen MAC und kann also nichts testen oder anpassen.

**Comment by ghost** [comment]
Ah okay. Bei mir lief die Version nicht, da mein Mac einen dieser M1 Chips besitzt und ich für arm64 kompilieren musste.
