### ISSUE TITLE
Speicherort der Abos im MTPlayer

### ISSUE THREAD

**Issue by n3zvtVsJFbECVKsKJDNS** [xaverW/MTPlayer#3]
Hallo zusammen, weiß irgendwer wo die Abos gespeichert sind, bzw. gibt es eine Möglichkeiten sie zu exportieren/importieren? Bg

**Comment by xaverW** [comment]
in deinem User-Verzeichnis im Ordner ".p2Mtplayer"
(der Ordner ist standardmäßig unsichtbar, also einschalten: "alle anzeigen")
dort in der Datei: "mtplayer.xml" liegen alle Einstellungen

das ist ein Abo:
`<Abonnement><Nr>11</Nr><aktiv>true</aktiv><Name>Der Fernsehfilm der Woche</Name><Aufloesung>normal</Aufloesung><Sender>ZDF</Sender><Thema>Der Fernsehfilm der Woche</Thema><Thema-exakt>true</Thema-exakt><Zeitraum>alles</Zeitraum><Mindestdauer>30</Mindestdauer><Maxdauer>alles</Maxdauer><Zielpfad>film</Zielpfad><letztes_Abo>05.05.2020</letztes_Abo><Programmset>Standard Speichern neu</Programmset></Abonnement>
` 

das ist es jetzt nochmal ohne Pfadangabe:
`<Abonnement><Nr>11</Nr><aktiv>true</aktiv><Name>Der Fernsehfilm der Woche</Name><Aufloesung>normal</Aufloesung><Sender>ZDF</Sender><Thema>Der Fernsehfilm der Woche</Thema><Thema-exakt>true</Thema-exakt><Zeitraum>alles</Zeitraum><Mindestdauer>30</Mindestdauer><Maxdauer>alles</Maxdauer><letztes_Abo>05.05.2020</letztes_Abo><Programmset>Standard Speichern neu</Programmset></Abonnement>
`

**Comment by n3zvtVsJFbECVKsKJDNS** [comment]
Guten Morgen,  vielen Dank für die ausführliche Erklärung. Hast mir sehr geholfen. Schönes WE noch und viele Grüße, :-)
