### ISSUE TITLE
Abos für exakte Substrings anlegen

### ISSUE THREAD

**Issue by tteichma** [xaverW/MTPlayer#4]
Hallo,

ich würde gerne ein Abo für die Artereihe "Re:" anlegen. Alle entsprechenden Titel fangen mit "Re: " an, aber wenn ich das als Kriterium im Abo eintrage werden mir alle Sendungen die irgendwo im Titel "re" enthalten mit angezeigt.

Ist das möglich oder wäre es perspektivisch möglich das zu ermöglichen?

Danke!

**Comment by xaverW** [comment]
Hi,

musste jetzt auch etwas spielen :)

geht so:

Sender: Arte
Titel: #:re:.*


In allen Feldern (wenn nicht "exakt" eingestellt ist) kann auch mit
regulären Ausdrücken gesucht werden. Diese müssen mit "#:" eingeleitet
werden. Auch bei den regulären Ausdrücken wird nicht zwischen Groß- und
Kleinschreibung unterschieden. #:Abend.* Das bedeutet z.B.: Es werden
alle Filme gefunden, die im jeweiligen Feld mit "Abend" beginnen.

https://www.p2tools.de/mtplayer/manual/filter.html

https://de.wikipedia.org/wiki/Regul%C3%A4rer_Ausdruck


Grüße
Xaver

**Comment by tteichma** [comment]
Danke, genau so etwas habe ich gesucht.
