### ISSUE TITLE
BR-Downoalds scheitern mit "No subject alternative DNS name matching cdn-storage.br.de found."

### ISSUE THREAD

**Issue by u-le** [xaverW/MTPlayer#5]
Ich bin kürzlich auf MTPlayer als bessere Alternative zu Mediathek-View gestoßen. Erstmal vielen Dank dafür!

Leider habe ich regelmäßig Probleme mit Downloads von BR-Sendungen. Auch wenn bei derselben Sendung "ARD" als Sender aufgeführt wird, klappte der Download nicht. Fehlermeldung ist: 
"Der Download hatte einen Fehler: No subject alternative DNS name matching cdn-storage.br.de found."

Wenn ich die URL des Downloads aber über FreeDownloadManager herunterlade, klappt der Download. Die URL wird also offenbar richtig analysiert.

**Comment by xaverW** [comment]
kannst du mir da noch ein logfile zu mailen?
(liegen im Config-Ordner: ".p2Mtplayer/Log" oder bei Win: "p2Mtplayer/Log"

w.xaver --at-- googlemail.com
danke
Xaver

**Comment by u-le** [comment]
Hallo Xaver,
ich hatte Dir ein Log an die angegeben Mail-Adresse gesandt. Ist das angekommen? Hast Du was damit anfangen können?

**Comment by xaverW** [comment]
Hi,
ja habe ich bekommen:

    javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching cdn-storage.br.de found.

das ist der Fehler, Problem ist, dass das nicht bei jedem OS auftritt. Es fehlen SSL-Zertifikate. Bei mir (Linux) tritt der Fehler nie auf und bei einem Win10 bei mir, tritt der Fehler (inzwischen?) auch nicht mehr bei deinen URLs auf. Bin noch am überlegen, wie das am besten umschifft werden kann. Könntest die URLs bei dir vielleicht auch nochmal testen?
Eine Möglichkeit wäre, die URL nach diesem Feheler anzupassen (http statt https). Bei den bis jetzt getesteten wäre es möglich.

Grüße

**Comment by u-le** [comment]
Hi,
ja der Fehler tritt nach wie vor auf (Win10). Wenn es an einem fehlenden Zertifikat liegt, sollte die Datei doch per FreeDownloadManager auch nicht downloadbar sein. Beide sollten doch auf dieselben Zertifikate im OS zugreifen, oder täusche ich mich? Kenne mich da nicht so aus.

Wie kann ich die URL in MTPlayer anpassen? Die wird doch vom Crawler geliefert und in MTPlayer über den "Download ändern"-Dialog nur angezeigt. Ich seh keine Möglichkeit, die anzupassen.

**Comment by xaverW** [comment]
Hi,
die URL kannst du im Programm nicht ändern.
Bei falschem oder fehlendem Zertifikat bricht das Programm aus Sicherheitsgründen ab (die URL ist ja fehlerhaft). Der Download kann aber trotzdem klappen. Das Zertifikat ist nur eine Beglaubigung, dass die URL OK ist, quasi wie eine Unterschrift unter den Download-Link.

**Comment by u-le** [comment]
Was meintest Du dann mit "... die URL nach diesem Fehler anzupassen"? Außerhalb von MTPlayer funktioniert sie ja problemlos, sowohl mit FDM als auch im Browser. Also muss das Zertifikat ja vorhanden sein. Nur MTPlayer kann es scheint's nicht auslesen, oder?

**Comment by u-le** [comment]
Hallo Xaver,
das Problem besteht immer noch. Irgendeine Chance das zu beheben?
Ich habe mir Deinen Post oben nochmal durchgelesen. Meintest Du, dass Du im Programm nach Auftreten des Fehlers automatisch auf http ändern könntest? das wäre super. Ich hatte das wohl missverstanden und gemeint, ich müsse irgendwas anpasssen.

**Comment by xaverW** [comment]
Hi,

lade gerade ein neues daily hoch:
https://www.p2tools.de/mtplayer/download.html

da habe ich was angepasst. Könntest du das mal ausprobieren? In den
Einstellungen->Download kann man die Überprüfung der SSL-Zertifikate
abschalten. Dann sollte der Download auch bei fehlendem Zertifikat
laufen.

Mal mit ausgeschalteter- und mal mit eingeschalteter Überprüfung. Wäre
super.

Grüße


Am Wed, 02 Jun 2021 12:22:13 -0700
schrieb u-le ***@***.***>:

> Hallo Xaver,
> das Problem besteht immer noch. Irgendeine Chance das zu beheben?
> Ich habe mir Deinen Post oben nochmal durchgelesen. Meintest Du, dass
> Du im Programm nach Auftreten des Fehlers automatisch auf http ändern
> könntest? das wäre super. Ich hatte das wohl missverstanden und
> gemeint, ich müsse irgendwas anpasssen.
>

**Comment by u-le** [comment]
Hi,

habs gerade ausprobiert und einen interessanten Befund: Mit der Daily-Version klappt der Download auch ohne dass ich die SSL-Prüfung abschalte. Hab denselben DL dann testweise nochmal in der Release-Version gestartet, dort ist er gescheitert.
Wieder zurück in der Daily, DL klappt.
Du musst da wohl noch was anderes gemacht haben, was den BR-Downloads auf die Sprünge hilft ... :-o
(Oder der Schalter ist buggy und SSL immer abgeschaltet ;-D )

Hab mit diesen beiden Dowwnloads getestet:
https://cdn-storage.br.de/MUJIuUOVBwQIbtCCBLzGiLC1uwQoNA4p_AES/_-9S/_2v6571S/287f2925-709a-49b5-a83f-4506e7cf7ceb_X.mp4
https://cdn-storage.br.de/b7/2021-03/18/536292cc882511eb8ee102420a00050a_X.mp4

Grüße und Danke!
