### ISSUE TITLE
Downloadgeschwindigkeit nur bei ZDF, ARD und ARTE gaaanz langsam?

### ISSUE THREAD

**Issue by n3zvtVsJFbECVKsKJDNS** [xaverW/MTPlayer#6]
Hallo,

weiß irgendwer, warum neuderdings seit Wochen die Downloadgeschwindigkeit nur bei ZDF, ARD  und ARTE in kilobite Bereich liegen, jedoch andere Sender mit voller Downloadauslastung im MB-Bereich sehr wohl funktionieren?
Wäre unendlich dankbar, wenn jemand eine Lösung hätte.

PS: ein Länderfilter wird es wohl nicht sein, da ich in Österreich bin. Denn sauge ich den gleichen Film bspw. direkt von der ZDF-Mediathek oder ARD-Mediathek im Webbrowser, dann funktionierts ja auch ohne Drosselung.

**Comment by xaverW** [comment]
Hi,
hier in DE ist mir das noch nicht aufgefallen?? Hast du mal versucht, den "UserAgent" in den Einstellungen zu ändern (z.B. "Mozilla/5.0") wenns im Browser schneller läuft.

**Comment by xaverW** [comment]
Ist das noch aktuell?
