### ISSUE TITLE
Wiederaufnahme unterbrochener Downloads - Zurückstellen?

### ISSUE THREAD

**Issue by u-le** [xaverW/MTPlayer#7]
Manchmal ist es erforderlich, Downloads zu unterbrechen und später wiederaufnehemn zu können. Hierzu habe ich bisher in MTP keine Möglichkeit gefunden. Zwar bleiben die nicht abgeschlossenen DL's in der Download-Liste. Dort sind aber wegen der Abos sehr viel mehr DL's verzeichnet als die bereits begonnenen.

Ich habe es mit Zurückstellen versucht, aber ich verstehe nicht, was das tut. Ich hätte erwartet, dass dadurch ein Flag in der Spalte zurückgestellt gesetzt wird, sodass ich danach filtern oder sortieren kann. Aber wenn ich einen gestarteten Download zurückstelle, passiert gar nichts. Wenn ich einen nicht gestarteten zurückstelle, verschwindet er komplett aus der DL-Liste.

Ist mein Anwendungsfall in MTP darstellbar? Wie sollte Zurückstellen funktionieren - ich finde dazu nichts in der Doku?

**Comment by xaverW** [comment]
Hallo,

> Manchmal ist es erforderlich, Downloads zu unterbrechen und später

das macht der Button "Stop" (mit dem Quadrat). Damit wird der Download
gestoppt. Er kann dann einfach durch "Starten" (Dreieck) wieder
gestartet werden. Je nach Art des Downloads (einfacher Download) wird
er weitergeführt oder (Download der durch ein Programm geladen werden
muss: Stream, können nicht weitergeführt werden) wird wieder von vorne
begonnen.


> Ich habe es mit Zurückstellen versucht, aber ich verstehe nicht, was

das meint, dass Downloads (und nur die noch nicht gestarteten) wieder
aus der Downloadliste entfernt werden. Beim nächsten Suchen nach
Downoads (Button: 2 gedrehte Pfeile) werden die zurückgestellten dann
wieder eingereiht. Ist gedacht um bei vielen Downloads die Übersicht zu
behalten.
