### ISSUE TITLE
Download bei einigen Servern nicht möglich - Zertifikatfehler

### ISSUE THREAD

**Issue by MichaelZ4714** [xaverW/MTPlayer#8]
MTPlayer 12 auf Windows 11

Downloads von einigen Servern brechen beim Start mit einem Fehler ab, bedingt durch eine falsche Auswertung des Zertifikats. Beispiel:

Nord bei Nordwest Canasta (19)
https://pd-videos.daserste.de/int/2022/12/30/64146415-f01d-4fb9-8444-9161c547f639/JOB_273396_sendeton_960x540-50p-1600kbit.mp4

Fehler:
javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching pd-videos.daserste.de found.

Im Browser lässt sich der Link fehlerfrei öffnen. Das Zertifikat lautet auf mcdn.daserste.de und enthält den alternativen Namen pd-videos.daserste.de. Das Zertifikat habe ich beigefügt, ebenso wie einen Auszug aus dem Log.
[mcdn.daserste.de.zip](https://github.com/xaverW/MTPlayer/files/10394334/mcdn.daserste.de.zip)
[P2Tools_0.zip](https://github.com/xaverW/MTPlayer/files/10394343/P2Tools_0.zip)

**Comment by MichaelZ4714** [comment]
Der Fehler tritt nicht auf wenn statt der mitgelieferten JRE in den Ordner Java die Azul Zulu OpenJDK 11.0.17+8-LTS JRE FX kopiert wird.

**Comment by xaverW** [comment]
Da fehlen warscheinlich die Root-Zertifikate im jre. Deswegen ist das Problem nicht auf jedem BS und mit jedem JRE vorhanden.
Werde mir da was überlegen, evt. ist es besser, eine Fehlermeldung zu zeigen ("Zertifikat fehlt", Download trotzdem starten??) oder so ähnlich??

Als Workarount: In den Einstellungen (Download->SSL DownloadURLs) kann man die Prüfung abschalten. Dann klappt zumindest der Download

**Comment by MichaelZ4714** [comment]
Die Einstellungsmöglichkeit hatte ich übersehen :-(   Ich hatte auch die Closed Issues nicht gesehen, es gab ja bereits #5 zu diesem Problem.
Gibt es in Java eventuell die Möglichkeit, auf die CA-Liste des Betriebssystems umzuschalten?

**Comment by xaverW** [comment]
In der neuen Version kommt jetzt bei einem Zertifikatsfehler eine Meldung: Trotzdem laden? und man kann dann das Laden trotzdem fortsetzen. Der Download geht nicht mehr automatisch auf "Fehler"
