### ISSUE TITLE
Neue V13 verlangt Java V11

### ISSUE THREAD

**Issue by JMLatGitHub** [xaverW/MTPlayer#9]
Hallo

Wollte nur melden, dass beim Aufruf der neuen MTPlayer V13 zumindest unter Windows Java V11 verlangt, die Oracle-Webseite aufruft und Startvorgang abbricht.

V12 kommt mit Java V19.0.2 klar.

Gruß

**Comment by xaverW** [comment]
Hallo,

kannn es sein dass Java 19 nicht richtig installiert ist? Was wird angezeigt im Terminal:

java -version

Ich habs bei mir ausprobiert: Windows 10 64bit, Java 19.0.2 und das Programm startet, sowohl mit der exe als auch mit einem Doppelklick auf MTPlayer.jar

Java ist von da:
https://www.oracle.com/java/technologies/downloads/
https://download.oracle.com/java/19/latest/jdk-19_windows-x64_bin.exe

Grüße

**Comment by JMLatGitHub** [comment]
Ich verwende OpenJDK:

`java -version

openjdk version "19.0.2" 2023-01-1

OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)

OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode, sharing)`

V12 funktioniert tadellos damit.

**Comment by xaverW** [comment]
Java 11 ist die Mindest-Version aber das Programm läuft auch mit höheren Versionen.

Versuch doch mal das Programm aus einer Konsole heraus zu starten:
im Programmordner:

Java -jar MTPlayer.jar

**Comment by JMLatGitHub** [comment]
Ja, aus der Kommandozeile startet die Anwendung. Das Fehlverhalten tritt nur auf, wenn ich einen Shortcut von "MTPlayer__Windows.exe" auf den Desktop erstelle und so die Anwendung starten will (oder per Doppelklick direkt auf der Datei). Mit der MTPlayer V13 + Java-Version geht es.

**Comment by xaverW** [comment]
Kannst du mir den Pfad in dem dein Java ist (das nicht gefunden wird), schicken?
Die ".exe" Datei ist eigenlich nur ein "Startskript" das die Programmdatei MTPlayer.jar startet. 
Wenn Java richtig installiert ist, startet das Programm auch mit einem Doppelklick darauf. Da das aber nicht immer klappt, gibts zusätzich die ".exe"

**Comment by JMLatGitHub** [comment]
'JAVA_HOME = C:\Program Files\Eclipse Adoptium\jre-19.0.2.7-hotspot\
Path = C:\Program Files\Eclipse Adoptium\jre-19.0.2.7-hotspot\bin; %JAVA_HOME%\bin'

wobei %JAVA_HOME%\bin in C:\Program Files\Eclipse Adoptium\jre-19.0.2.7-hotspot\\\bin  resultiert, was im Normalfall kein Problem darstellen sollte...

Gruß

**Comment by JMLatGitHub** [comment]
Wenn ich den doppelten \ entferne, ändert sich nichts.
Klicke ich direkt auf MTPlayer.jar, dann startet die Anwendung ohne zu meckern.
